kind: Service
apiVersion: v1
metadata:
  name: mysql-service
spec:
  type: NodePort
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30006

---
kind: Service
apiVersion: v1
metadata:
  name: mongodb-service
spec:
  type: NodePort
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30017