kind: Service
apiVersion: v1
metadata:
  name: spring-service
spec:
  type: ClusterIP
  selector:
    app: spring-app
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080