kind: Service
apiVersion: v1
metadata:
  name: spring-service
spec:
  type: NodePort
  selector:
    app: spring-app
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080