spring:
  data:
    mongodb:
      uri: mongodb://admin:wjdxhd12@default-mongodb-service-181b2-100187552-77508158c21f.kr.lb.naverncp.com:17017/test?authMechanism=SCRAM-SHA-256
      auto-index-creation: true
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: dh7672@@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.type: trace

# application.yml
ai:
  url: "https://your-ai-service-url.com"

